mcc_lookup = {
    5712: "Furniture, home furnishings and equipment shops and manufacturers, except appliances",
    5719: "Miscellaneous home furnishing speciality shops",
    5722: "Household appliance shops",
    5732: "Electronics shops",
    5733: "Music Stores—Musical Instruments, Pianos, Sheet Music",
    5734: "Computer software outlets",
    5812: "Eating places and restaurants",
    5815: "Digital Goods-Media, Books, Movies, Music",
    5816: "Digital Goods-Games",
    5817: "Digital Goods-Software Applications (excluding games)",
    5941: "Sporting goods shops",
    5945: "Hobby, toy and game shops",
    5947: "Gift, card, novelty and souvenir shops",
    5950: "Glassware and crystal shops",
    5970: "Artist supply and craft shops",
    5977: "Cosmetic shops",
    5995: "Pet shops, pet food and supplies",
    5999: "Miscellaneous and Specialty Retail Stores",
    4112: "Passenger railways",
    4131: "Bus lines",
    4214: "Motor freight carriers and trucking - local and long distance, moving and storage companies and local delivery",
    4215: "Courier services - air and ground and freight forwarders",
    4225: "Public warehousing and storage - farm products, refrigerated goods and household goods",
    5065: "Electrical parts and equipment",
    5072: "Hardware equipment and supplies",
    5200: "Home supply warehouse outlets",
    5251: "Hardware Stores",
    5311: "Department stores",
    5331: "Variety stores",
    5399: "Miscellaneous general merchandise",
    5499: "Miscellaneous food shops - convenience and speciality retail outlets",
    5533: "Automotive parts and accessories outlets",
    5611: "Men’s and boys’ clothing and accessory shops",
    5621: "Women’s ready-to-wear shops",
    5631: "Women’s accessory and speciality shops",
    5641: "Children’s and infants’ wear shops",
    5651: "Family clothing shops",
    5655: "Sports and riding apparel shops",
    5661: "Shoe shops",
    5691: "Men’s and women’s clothing shops",
    5698: "Wig and toupee shops",
    5699: "Miscellaneous apparel and accessory shops",
    7278: "用7399代替",
    7298: "Health and beauty spas",
    7375: "Information Retrieval Services",
    7399: "Business services - not elsewhere classified",
    7512: "Automobile rentals",
    8043: "Opticians, optical goods and eyeglasses",
    7999: "Recreation Services–Not Elsewhere Classified",
    4722: "Travel Agencies and Tour Operations",
    8299: "Schools And Educational Services–Not Elsewhere Classified"
}